# Generated by Django 2.0 on 2017-12-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pet name')),
                ('breed', models.CharField(max_length=30, verbose_name='Breed')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('sound', models.CharField(max_length=10, verbose_name='Breed')),
            ],
        ),
    ]
